[versions]
# libraries
jspecify = "1.0.0"
annotations = "26.0.2"

# testing tool
junit = "5.12.1"

[libraries]
# libraries
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

# testing tool
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
